language: php

php:
    - "5.6"

env:
    - WP_VERSION=master WP_MULTISITE=0 #Current stable release

matrix:
  include:
    #   php  5.6
    - php: "5.6"
      env: WP_VERSION=master WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=master WP_MULTISITE=1
    - php: "5.6"
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.7 WP_MULTISITE=1
    - php: "5.6"
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.3 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: "5.5"
      env: WP_VERSION=master WP_MULTISITE=0
    - php: "5.4"
      env: WP_VERSION=master WP_MULTISITE=0
    - php: "5.3"
      env: WP_VERSION=master WP_MULTISITE=0
    - php: "7.0"
      env: WP_VERSION=master WP_MULTISITE=0
    - php: "7.0"
      env: WP_VERSION=master WP_MULTISITE=1
    - php: "hhvm"
      env: WP_VERSION=master WP_MULTISITE=0
    - php: "nightly"
      env: WP_VERSION=master WP_MULTISITE=0
  allow_failures:
    - php: "hhvm"
    - php: "nightly"

before_script:
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone --depth=1 --branch $WP_VERSION git://develop.git.wordpress.org/ /tmp/wordpress
    - cd ..
    - mv $PLUGIN_SLUG "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - cd /tmp/wordpress
    - git checkout $WP_VERSION
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"

script: phpunit

sudo: false
