name: PHPLint

on: [ push ]

jobs:
  phplint:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]
        php-versions: [ '7.4' ]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, fileinfo, zip, mbstring
          ini-values: "post_max_size=256M"

      - name: Check PHP Version
        run: php -v

      - name: Update the composer.lock file
        run: composer update --lock

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check syntax errors
        run: ./vendor/bin/phplint
